<?php

namespace AppBundle\Repository;

/**
 * BusketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusketRepository extends \Doctrine\ORM\EntityRepository
{
}
