<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Busket;
use Doctrine\ORM\EntityRepository;

/**
 * BusketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusketRepository extends EntityRepository
{
    const DEFAULT_BUSKET_NAME = 'Default Busket';

    public function findDefaultBusket(): Busket
    {
        return $this->findOneBy(['name' => self::DEFAULT_BUSKET_NAME]);
    }
}
