<?php

namespace AppBundle\Repository;
use AppBundle\Entity\VatType;

/**
 * VatTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VatTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
